### ISSUE TITLE
cannot terraform init on v2

### ISSUE THREAD

**Issue by muharramwidaseta** [traveloka/terraform-github-repository#19]
when i do terraform init i got this error code
`Error downloading modules: Error loading modules: module github-repository_terraform-aws-xxtdata-app: Error parsing .terraform/modules/e10a15ab7e6d61fe083823eb1200cb45/main.tf: At 37:34: Unknown token: 37:34 IDENT var.dismiss_review_users`

**Comment by salvianreynaldi** [comment]
@muharramwidaseta you need terraform 0.12 for this module
